grass=true
mycelium=true
podzol=true
grass.snow=true
mycelium.snow=true
podzol.snow=true
grass.multilayer=false
texture.grass=blocks/grass_top
texture.grass_side=blocks/grass_side
texture.mycelium=blocks/mycelium_top
texture.podzol=blocks/dirt_podzol_top
texture.snow=blocks/snow
