name: build
on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip]')"
    runs-on: ubuntu-latest
    steps:
      -   name: checkout
          uses: actions/checkout@v7

      -   name: setup java
          uses: actions/setup-java@v5
          with:
            distribution: zulu
            java-version: 21

      -   name: setup gradle
          uses: gradle/actions/setup-gradle@v6
          with:
            cache-encryption-key: ${{ SECRETS.GRADLE_ENCRYPTION_KEY }}
            build-scan-publish: false
            build-scan-terms-of-use-url: https://gradle.com/terms-of-service
            build-scan-terms-of-use-agree: yes

      -   name: restore local gradle caches
          uses: actions/cache@v6
          with:
            key: gradle-local-cache-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', '**/*.gradle.kts', 'gradle.properties') }}
            restore-keys: |
              gradle-local-cache-${{ runner.os }}-
            path: |
              ./.gradle/loom-cache/
              ./.gradle/configuration-cache.enc
              ./buildSrc/build/

      -   name: unpack configuration cache
          run: |
            if [ -f ".gradle/configuration-cache.enc" ]; then
              openssl enc \
                -d \
                -aes-256-cbc \
                -pbkdf2 \
                -salt \
                -pass pass:"GRADLE_ENCRYPTION_KEY" \
                -in .gradle/configuration-cache.enc \
                -out /tmp/configuration-cache.tar

              mkdir -p .gradle/configuration-cache
              tar -xf /tmp/configuration-cache.tar -C .gradle/configuration-cache
            fi

      -   name: do the build
          run: ./gradlew assemble --stacktrace --no-daemon

      -   name: upload artifacts
          uses: actions/upload-artifact@v7
          with:
            name: argentum-artifacts-v${{ github.run_number }}
            path: |
              build/libs/*

      -   name: encrypt configuration cache
          run: |
            if [ -d ".gradle/configuration-cache" ]; then
              tar -cf /tmp/configuration-cache.tar -C .gradle/configuration-cache .
        
              openssl enc \
                -aes-256-cbc \
                -pbkdf2 \
                -salt \
                -pass pass:"GRADLE_ENCRYPTION_KEY" \
                -in /tmp/configuration-cache.tar \
                -out .gradle/configuration-cache.enc
            fi